
/gate/source/addSource punto1
/gate/source/punto1/setActivity 0.1 MBq

/gate/source/punto1/gps/centre 90 0 0 mm
/gate/source/punto1/gps/particle gamma

/gate/source/punto1/gps/energytype Mono
/gate/source/punto1/gps/monoenergy 511 keV

/gate/source/punto1/gps/angtype iso
/gate/source/punto1/gps/mintheta 89 deg
/gate/source/punto1/gps/maxtheta 91 deg

# /gate/source/punto1/gps/minphi 14.8 deg
# /gate/source/punto1/gps/maxphi 16.8 deg

/gate/source/punto1/gps/minphi 46 deg
/gate/source/punto1/gps/maxphi 49 deg

/gate/source/punto1/gps/pos/type Point
/gate/source/punto1/visualize cyan